<<<<<<< HEAD
version: '3'

services:
  email:
    image: maildev/maildev
    ports:
      - "25:25"
=======
version: '3'

services:
  email:
    image: maildev/maildev
    ports:
      - "25:25"
>>>>>>> 2b4725adb6f6a009f23bb7f3070c00c075837d1f
      - 8000:80