<<<<<<< HEAD
version: '3'

services:
  ssh:
    container_name: ssh
    image: rastasheep/ubuntu-sshd
    ports:
      - ${SSH_CLI_PORT}:${SSH_HOST_PORT}
    volumes:
=======
version: '3'

services:
  ssh:
    container_name: ssh
    image: rastasheep/ubuntu-sshd
    ports:
      - ${SSH_CLI_PORT}:${SSH_HOST_PORT}
    volumes:
>>>>>>> 2b4725adb6f6a009f23bb7f3070c00c075837d1f
      - ./home:/home