<<<<<<< HEAD
version: '3'

services:
  web:
    image: nginx
    ports:
      - "8000:80"
    volumes:
=======
version: '3'

services:
  web:
    image: nginx
    ports:
      - "8000:80"
    volumes:
>>>>>>> 2b4725adb6f6a009f23bb7f3070c00c075837d1f
      - ./www:/usr/share/nginx/html